# Generated by Django 5.0 on 2024-03-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roomdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_rooms', models.IntegerField(max_length=255)),
                ('type_of_room', models.CharField(max_length=255)),
                ('noofpeople', models.CharField(choices=[('adults', 'Adults'), ('children', 'Children')], max_length=20)),
            ],
        ),
    ]
